routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{
    DashboardController,
    penggunaController,
    datapengaduController,
    laporanController,
    jenisaduanController,
    AuthController,
    tanggapanController,
    MenungguController,
    ProfileController
};

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login'])->name('login.post');
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('profile', [ProfileController::class, 'update'])->name('profile.update');
    
    Route::get('/pengguna', [penggunaController::class, 'index']);
    Route::get('add-pengguna', [penggunaController::class, 'create'])->name('add-pengguna');
    Route::post('save-pengguna', [penggunaController::class, 'store'])->name('save-pengguna');
    Route::get('edit-pengguna/{id}', [penggunaController::class, 'edit'])->name('edit-pengguna');
    Route::post('update-pengguna/{id}', [penggunaController::class, 'update'])->name('update-pengguna');
    Route::get('delete-pengguna/{id}', [penggunaController::class, 'destroy'])->name('delete-pengguna');

    Route::get('/laporan', [laporanController::class, 'index']);
    Route::get('/add-laporan/{id}', [laporanController::class, 'create'])->name('add-laporan');
    // Route::get('/edit-tanggapan')
    Route::post('save-laporan', [laporanController::class, 'store'])->name('save-laporan');
    Route::get('delete-laporan/{id}', [laporanController::class, 'destroy'])->name('delete-laporan');
    Route::get('laporan/{id}', [laporanController::class, 'show'])->name('laporan.show');
    
    Route::get('/datapengadu', [datapengaduController::class, 'index']);
    Route::get('/pengadu', [datapengaduController::class, 'pengadu'])->name('pengadu');
    Route::get('add-pengadu', [datapengaduController::class, 'create'])->name('add-pengadu');
    Route::post('save-pengadu', [datapengaduController::class, 'store'])->name('save-pengadu');
    Route::get('edit-pengadu/{id}', [datapengaduController::class, 'edit'])->name('edit-pengadu');
    Route::post('update-pengadu/{id}', [datapengaduController::class, 'update'])->name('update-pengadu');
    Route::get('delete-pengadu/{id}', [datapengaduController::class, 'destroy'])->name('delete-pengadu');
    
    Route::get('/add-tanggapan/{id}', [tanggapanController::class, 'create'])->name('add-tanggapan'); 
    Route::get('/edit-tanggapan/{id}', [tanggapanController::class, 'edit'])->name('edit-tanggapan'); 
    Route::post('/save-tanggapan/{id}', [tanggapanController::class, 'update'])->name('save-tanggapan');
    Route::get('/delete-tanggapan', [tanggapanController::class, 'destroy'])->name('delete-tanggapan');
    Route::get('/selesai', [tanggapanController::class, 'index']);
    Route::get('selesai/{laporan:id}/pdf', [tanggapanController::class, 'print_pdf'])->name('selesai.pdf');
    
    Route::get('/ditanggapi', [MenungguController::class, 'index']);
    Route::get('/menunggu', [MenungguController::class, 'all']);
    Route::get('/edit-ditanggapi/{id}', [tanggapanController::class, 'editDitanggapi'])->name('edit-ditanggapi');
    Route::post('image-upload/{id?}', [App\Http\Controllers\laporanController::class, 'imageUploadPost'])->name('image.upload.post');
    Route::get('image-upload/{id?}', [App\Http\Controllers\laporanController::class, 'imageUpload'])->name('image.upload');
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends("layouts.app")
@section("title", "Dashboard")
@section("content")
    <div class="container-fluid px-4">
        <h1 class="mt-4">Hai {{Auth::user()->name}}!</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        <div class="row">
        <div class="col-xl-3 col-md-6">
            <div onclick="document.location.href='/menunggu'" class="card bg-primary text-white mb-4">
                <div class="card-body mx-auto">Total Pengaduan</div>
                <h1 class="card-body mx-auto">{{$laporan->total}}</h1>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>

            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div onclick="document.location.href='/ditanggapi'" class="card bg-warning text-white mb-4">
                <div class="card-body mx-auto">Pengaduan Menunggu</div>
                <h1 class="card-body mx-auto">{{$laporan->waiting}}</h1>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div onclick="document.location.href='/selesai   '" class="card bg-success text-white mb-4">
                <div class="card-body mx-auto">Pengaduan Selesai</div>
                <h1 class="card-body mx-auto">{{$laporan->finished}}</h1>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        @if(auth()->user()->role=='admin')
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body mx-auto">Pengadu</div>
                <h1 class="card-body mx-auto">{{$pengadu}}</h1>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{{ route('pengadu') }}">View Details</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection

resources/views/datapengadu.blade.php
@extends("layouts.app")
@section("title", "Data Pengadu")

@section("custom-style")

<style>
    .no-wrap {
        /* text-overflow: ellipse;
        white-space: nowrap;
        overflow: hidden; */
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }
</style>

@section("content")
<div class="container-fluid">
    <br>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
        <li class="breadcrumb-item active">Laporan Saya</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
            <a href="{{ route('add-pengadu') }}" class="btn btn-primary" id="createPengadu"
                style="margin-left: 1rem">
                Tambahkan Laporan
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Aduan</th>
                            <th>Picture</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach ($laporans as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td><p class="no-wrap">{!! nl2br($item->aduan) !!}</p></td>
                        <td>
                            @if($item->picture_awal == NULL)
                            @else
                            <img width="150px" height="100px"  src="{{$item->picture_awal}}" alt=""></td>
                            @endif
                        <td>
                            <a href="{{ route('laporan.show', $item->id) }}" class="btn btn-outline-info">
                                Show
                            </a>
                            <a href="{{ url('edit-pengadu', $item->id) }}" class="btn btn-outline-danger">Edit</a>
                            <a href="{{ url('delete-pengadu', $item->id) }}" class="btn btn-outline-danger"><i class="bi bi-trash">Hapus</i></a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ditanggapi.blade.php
@extends("layouts.app")
<!-- modal image popup -->
@section("title", "Selesai")
@section('custom-style')
<style>
    .no-wrap {
        /* text-overflow: ellipse;
        white-space: nowrap;
        overflow: hidden; */
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }
</style>
@section("content")


<div class="modal fade" id="img" tabindex="-1" role="dialog" aria-labelledby="img">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <img style="max-height:430px;" id="myImage" class="img-responsive" src="" alt="">
            </div>
            <div class="modal-footer">
                <button type="bxutton" class="btn btn-danger center-block" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">  



    <div class="container-fluid">
        <br>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Pengaduan</li>
            <li class="breadcrumb-item active">Selesai</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
            <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
                <b>Laporan</b>  
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Pengadu</th>
                                <th>Aduan</th>
                                <th>Picture Awal</th>
                                <th>Tanggapan</th>
                                <th>Picture</th>
                                @if(Auth::user()->role == "admin")
                                <th>Aksi</th>
                                @else
                                @endif
                        </thead>
                        <tbody>
                    @isset($laporans)
                        @foreach ($laporan as $item)
                        @if($item->picture != null && $item->picture != "")
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td><a href="{{ route('laporan.show', $item->id) }}">{{ $item->name }}</a></td>
                                <td><p class="no-wrap">{!! nl2br($item->aduan) !!}</p></td>
                                <td><img width="150px" height="100px"  src="{{$item->picture_awal}}" alt=""></td>
                                <td><p class="no-wrap">{!! nl2br($item->tanggapan) !!}</p></td>
                                    <td>
                                    <a href="#img" data-id="{{ $item->picture }}" class="openImageDialog thumbnail" data-toggle="modal">
                                        <img src="{{ $item->picture }}" width="200px"
                                        height="100px">
                                    </a>
                                    </td>
                                
                                @if(request()->user()->role == "admin")
                                    <td>
                                        <a href="delete-tanggapan?id={{$item->id}}" class="btn btn-outline-danger">Hapus</a>
                                        <a href="selesai/{{$item->id}}/pdf" class="btn btn-outline-success">Cetak</a>
                                    </td>
                                @endif
                            </tr>
                            @endif
                        @endforeach
                    @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script type="text/javascript">

    $(document).on("click", ".openImageDialog", function () {
        console.log('Ok');
    });


    $(document).on("click", ".openImageDialog", function () {
        var myImageId = $(this).data('id');
        $(".modal-body #myImage").attr("src", myImageId);
    });
</script>
@endsection

resources/views/imageUpload.blade.php
@extends('layouts.app')
@section("content")

<div class="section-header">
    <!-- <H1>image upload</H1>   -->
</div>

<div class="section-body">
    <div class="card">
        <div class="card-header">
            <h4>Upload Image </h4>
        </div>
            <div class="card-body">
                <div class="container">
                    <div class="panel panel-primary">
                        <div class="panel-heading"><h2>image upload</h2></div>
                            <div class="panel-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                <!-- <button type="button" class="close" data-dismiss="alert">×</button> -->
                                <strong>{{ $message }}</strong>
                                </div>
                                <img width="50%"height="50%" src="{{Session::get('picture')}}">
                            @endif
                    
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    
                        <form action="{{route('image.upload.post')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">

                            <input type="hidden" name="id" id="id" value="{{$id}}">

                                <div class="col-md-6">
                                    <input type="file" name="picture" class="form-control">
                                </div>
                    
                                <div class="col-md-6">
                                    <button type="submit" class="btn btn-success">Upload</button>
                                    <a class="btn btn-primary" href="/ditanggapi">Back</a>
                                </div>
                    
                            </div>
                        </form>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

function triggerImage(){
        var x = document.getElementById("myFile");
        var txt = "";
        if ('files' in x) {
            if (x.files.length == 0) {
                txt = "Select one or more files.";
            } else {
                for (var i = 0; i < x.files.length; i++) {
                txt += "<br><strong>" + (i+1) + ". file</strong><br>";
                var file = x.files[i];
                    if ('name' in file) {
                        txt += "name: " + file.name + "<br>";
                    }
                    if ('size' in file) {
                        txt += "size: " + file.size + " bytes <br>";
                    }
                }
            }
        } else {
            if (x.value == "") {
                txt += "Select one or more files.";
            } else {
                txt += "The files property is not supported by your browser!";
                txt  += "<br>The path of the selected file: " + x.value;
            }
        }
        // $name = $request->input('name');
        // $getimageName = $name.'.'.$request->image->getClientOriginalExtension();
        // $request->image->move(public_path('images'), $getimageName);
        // document.getElementById("myFile").innerHTML = txt;
    }
    </script>
@endsection

resources/views/jenisaduan.blade.php
@extends("layouts.app")
@section("title", "Jenis Aduan")
@section("content")
    <div class="container-fluid">
        <br>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Master Data</li>
            <li class="breadcrumb-item active">Jenis Aduan</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
            <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
                Jenis Aduan 
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @isset($jenisaduans)
                                @foreach ($jenisaduans as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->jenis }}</td>
                                        <td>
                                        <a href="{{ url('add-laporan', $item->id) }}" class="btn btn-outline-secondary">Laporkan</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection 

resources/views/laporan.blade.php
@extends("layouts.app")
@section("title", "laporan")
@section("content")
<!-- Modal Picture
<meta name="csrf-token" content="{{ csrf_token() }}" />
<div class="modal fade" id="modal_image" aria-labelledby="modal_image" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_image">Image Upload</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" id="picture" method="post" enctype="multipart/form-data">
                @csrf
                
                <div class="modal-body">
                    <div class="form-group">
                            <label for="">Upload File</label><br>
                            <input multiple type="file" name="picture[]" id="picture">
                        </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger btn_submit" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button id="btnAdd" type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i></i> Add</button>
                </div>
            </form>
        </div>
    </div>
</div> -->





<div class="container-fluid">
    <br>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
        <li class="breadcrumb-item active">Laporan</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
        <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
            Laporan 
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Pengadu</th>
                            <th>Aduan</th>
                            <th>Picture</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($laporan as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->aduan }}</td>
                            <td>{{ $item->picture }}</td>
                            <td>
                                <a href="{{ url('delete-laporan', $item->id_laporan) }}" class="btn btn-outline-danger">Hapus</a>
                                <a href="{{ url('add-tanggapan', $item->id_laporan) }}" class="btn btn-outline-secondary">{{ $item->tanggapan ? "Edit tanggapan" : "Tanggapi" }}</a>
                                {{-- <a href="{{ route('image.upload', $item->id_laporan) }}" class="btn btn-outline-primary" >Upload Image</a> --}}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/menunggu.blade.php
@extends("layouts.app")
@section("title", "Menunggu")

@section('custom-style')
<style>
    .no-wrap {
        /* text-overflow: ellipse;
        white-space: nowrap;
        overflow: hidden; */
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }
</style>

@section("content")
<div class="container-fluid">
    <br>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
        <li class="breadcrumb-item active">Pengaduan</li>
        <li class="breadcrumb-item active">Menunggu</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
        <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
            Laporan 
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Pengadu</th>
                            <th>Aduan</th>
                            <th>Picture Awal</th>
                            @if(Auth::user()->role == "admin")
                            <th>Aksi</th>
                            @else
                            @endif
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($laporan as $lapor)
                        <tr>
                            @if($lapor->tanggapan == NULL)
                            <td>{{ $loop->iteration }}</td>
                            <td><a href="{{ route('laporan.show', $lapor->id) }}" class="text-decoration-none">{{ $lapor->name }}</a></td>
                            <td><p class="no-wrap">{!! nl2br($lapor->aduan)  !!}</p></td>
                            <td><img width="150px" height="100px"  src="{{$lapor->picture_awal}}" alt=""></td>
                            @if(Auth::user()->role == "admin")
                            <td>
                                <a href="add-tanggapan/{{$lapor->id}}" class="btn btn-outline-primary">Tanggapi</a>
                                <a href="delete-tanggapan?id={{$lapor->id}}" class="btn btn-outline-danger">Hapus</a>
                            </td>
                            @endif
                            @endif
                        </tr>
                    @endforeach
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pengguna.blade.php
@extends("layouts.app")
@section("title", "Pengguna")
@section("content")
<div class="container-fluid">
    <br>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item active">Pengguna</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
        <button action="action" onclick="window.history.go(-1); return false;" type="submit" data-original-title="Kembali" title="Kembali" data-toggle="tooltip" class="btn btn-dark" >
                <i class="fas fa-arrow-circle-left"></i>
            </button>
            Data Pengguna 
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>No Hp</th>
                            <th>Alamat</th>
                            <th>Level</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($penggunas as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->no_hp }}</td>
                            <td>{{ $item->alamat }}</td>
                            <td>{{ $item->role }}</td>
                            <td>
                                <a href="{{ url('edit-pengguna', $item->id) }}" class="btn btn-outline-secondary">Edit</a>
                                <a href="{{ url('delete-pengguna', $item->id) }}" class="btn btn-outline-danger">Hapus</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>